version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - sam build

  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-eine28t2pxit --output-template-file output-template.yaml

artifacts:
  files:
    - output-template.yaml