version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cd HelloWorldFunction
      - mvn clean package

artifacts:
  files:
    - template.yaml
    - HelloWorldFunction/target/*.jar