AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  uploads-notification

  Sample SAM Template for uploads-notification

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  UploadsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UploadsNotificationFunction
      Runtime: java17
      Handler: helloworld.App::handleRequest
      CodeUri: HelloWorldFunction
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName: uploads-notification-topic